version: "3"

services:
    php:
        container_name: php
        restart: always
        build: docker/php
        working_dir: /usr/share/nginx/html
        volumes:
            - ./docker/php/conf.d:$PHP_INI_DIR/conf.d
            - .:/usr/share/nginx/html
    composer:
        container_name: composer
        build:
            context: docker/php
            dockerfile: Dockerfile
        entrypoint: composer
        volumes:
            - .:/home/user
